name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  container-name:
    description: 'Docker container name to use'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    run: |
      set -euxo pipefail

      CONTAINER_NAME=${{ inputs.container-name }}
      TAG=runtimeverificationinc/${CONTAINER_NAME}

      REPO_ROOT=$(realpath "${{ github.action_path }}/../../../")
      K_VERSION=$(cat "${REPO_ROOT}/deps/k_release")
      UV_VERSION=$(cat "${REPO_ROOT}/deps/uv_release")

      docker build .                                \
        --file ${{ github.action_path }}/Dockerfile \
        --tag ${TAG}                                \
        --build-arg K_VERSION=${K_VERSION}          \
        --build-arg UV_VERSION=${UV_VERSION}

      docker run                          \
        --name ${CONTAINER_NAME}          \
        --rm                              \
        --interactive                     \
        --tty                             \
        --detach                          \
        ${TAG}

      docker cp --archive . ${CONTAINER_NAME}:/home/user
